name: Deploy Build Artifacts

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [18.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    - run: npm run build-bin
    - name: Install SSH key
      uses: shimataro/ssh-key-action@v2
      with:
        key: ${{ secrets.SSH_KEY }}
        known_hosts: ${{ secrets.KNOWN_HOSTS }}
    - name: copy assets to server
      run: rsync -r ./dist/aoe-taunt-bot data alimg@141.147.76.96:/home/alimg
    - name: restart the service
      run: ssh alimg@141.147.76.96 -f 'systemctl --user restart aoe-taunt-bot'